### ISSUE TITLE
issue accessing environment variables

### ISSUE THREAD

**Issue by ASSAF1er** [rasengan-dev/rasenganjs#6]
I have a .env file at the root of my project with an env variable <b>RASENGAN_MY_VARIABLE</b> and I want to access it in a component.

I actually have <b>import.meta.env.RASENGAN_MY_VARIABLE;</b> in the component

But when I try <b>console.log(RASENGAN_MY_VARIABLE)</b> it returns an error saying the variable is not defined

**Comment by dilane3** [comment]
> I have a .env file at the root of my project with an env variable RASENGAN_MY_VARIABLE and I want to access it in a component.
> 
> I actually have import.meta.env.RASENGAN_MY_VARIABLE; in the component
> 
> But when I try console.log(RASENGAN_MY_VARIABLE) it returns an error saying the variable is not defined

Hello @ASSAF1er 

Please can you provide a simple screenshot of your **.env** file and the file where you are **importing your environment variable** ?

I want to know exactly how the problem occures.
