### ISSUE TITLE
Error while trying to run Rasengan app in development mode using the command 'rasengan dev'

### ISSUE THREAD

**Issue by EssiJunior** [rasengan-dev/rasenganjs#8]
### This is the error message:

**_The term 'rasengan' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again._**

I think this suggests installing **rasengan** CLI. My mistake maye be, but in the documentation I haven't seen a section specifying it. 

I will be happy to have a fix to this, thanks.

**Comment by dilane3** [comment]
> ### This is the error message:
> **_The term 'rasengan' is not recognized as a name of a cmdlet, function, script file, or executable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again._**
> 
> I think this suggests installing **rasengan** CLI. My mistake maye be, but in the documentation I haven't seen a section specifying it.
> 
> I will be happy to have a fix to this, thanks.

Hello @EssiJunior

Sorry for my late answer. Want to know if the error is still opened ? have you already found a way to resolve it ?

**Comment by dilane3** [comment]
After several investigation, it seems like you are trying to execute `rasengan dev` command directly, it's not possible.
You have to pass through a script from your package.json file and thenn run `npm run dev`.

Hope it's clear now.

I will close the issue.

**Comment by EssiJunior** [comment]
> After several investigation, it seems like you are trying to execute `rasengan dev` command directly, it's not possible.
> 
> You have to pass through a script from your package.json file and thenn run `npm run dev`.
> 
> 
> 
> Hope it's clear now.
> 
> 
> 
> I will close the issue.

Exactly, I tried to run `rasengan dev` on terminal.
